#!/usr/bin/env python3
"""Normalize clinical_domain field: 1,181 variants → ~50 canonical domains."""
import json
import re
import sys
from collections import Counter

CANONICAL_DOMAINS = {
    "Addiction Medicine",
    "Allergy & Immunology",
    "Anesthesiology",
    "Biomedical Engineering",
    "Cardiology",
    "Cell Biology",
    "Computational Biology",
    "Critical Care",
    "Dentistry",
    "Dermatology",
    "Emergency Medicine",
    "Endocrinology",
    "Environmental Health",
    "Epidemiology",
    "Gastroenterology",
    "Genetics & Genomics",
    "Geriatrics",
    "Hematology",
    "Hepatology",
    "Immunology",
    "Infectious Disease",
    "Internal Medicine",
    "Medical Informatics",
    "Microbiology",
    "Molecular Biology",
    "Nephrology",
    "Neurology",
    "Neuroscience",
    "Neurosurgery",
    "Nutrition",
    "Obstetrics & Gynecology",
    "Oncology",
    "Ophthalmology",
    "Orthopedics",
    "Otolaryngology",
    "Pain Medicine",
    "Palliative Care",
    "Pathology",
    "Pediatrics",
    "Pharmacology",
    "Psychiatry",
    "Public Health",
    "Pulmonology",
    "Radiology",
    "Rehabilitation Medicine",
    "Reproductive Medicine",
    "Rheumatology",
    "Surgery",
    "Toxicology",
    "Transplant Medicine",
    "Urology",
    "Veterinary Medicine",
    "Other",
}

# Direct mappings: raw (lowercased) → canonical
DIRECT_MAP = {
    # --- Formatting variants ---
    "infectious_disease": "Infectious Disease",
    "infectious-disease": "Infectious Disease",
    "infectious disease": "Infectious Disease",
    "infectious diseases": "Infectious Disease",
    "infectious": "Infectious Disease",
    "wound_care": "Surgery",
    "wound care": "Surgery",
    "wound healing": "Surgery",
    "burn wound healing": "Surgery",
    "general_medicine": "Internal Medicine",
    "general medicine": "Internal Medicine",
    "general": "Internal Medicine",
    "general_biology": "Cell Biology",
    "internal medicine": "Internal Medicine",
    "cardiovascular": "Cardiology",
    "cardiology": "Cardiology",
    "sports_medicine": "Orthopedics",
    "sports medicine": "Orthopedics",
    "pain_management": "Pain Medicine",
    "pain management": "Pain Medicine",
    "pain": "Pain Medicine",
    "pain medicine": "Pain Medicine",
    "elderly_care": "Geriatrics",
    "geriatric": "Geriatrics",
    "geriatric medicine": "Geriatrics",
    "geriatric_medicine": "Geriatrics",
    "geriatrics": "Geriatrics",
    "sleep_neurology": "Neurology",
    "sleep medicine": "Neurology",
    "mental_health": "Psychiatry",
    "mental health": "Psychiatry",
    "psychiatry": "Psychiatry",
    "neurology": "Neurology",
    "oncology": "Oncology",
    "dermatology": "Dermatology",
    "endocrinology": "Endocrinology",
    "gastroenterology": "Gastroenterology",
    "immunology": "Immunology",
    "bioinformatics": "Computational Biology",
    "bioinformatics-infrastructure": "Computational Biology",
    "structural bioinformatics": "Computational Biology",
    "obstetrics": "Obstetrics & Gynecology",
    "obstetric": "Obstetrics & Gynecology",
    "gynecology": "Obstetrics & Gynecology",
    "dentistry": "Dentistry",
    "genetics": "Genetics & Genomics",
    "genomics": "Genetics & Genomics",
    "genetic medicine": "Genetics & Genomics",
    "genetic disorders": "Genetics & Genomics",
    "genetic_disease": "Genetics & Genomics",
    "rare_genetic_disease": "Genetics & Genomics",
    "rare disease": "Genetics & Genomics",
    "rare disease pharmacology": "Pharmacology",
    "hematology": "Hematology",
    "nephrology": "Nephrology",
    "rheumatology": "Rheumatology",
    "pulmonology": "Pulmonology",
    "pulmonary": "Pulmonology",
    "respiratory": "Pulmonology",
    "ophthalmology": "Ophthalmology",
    "neuroscience": "Neuroscience",
    "pathophysiology": "Pathology",
    "pathology": "Pathology",
    "precision medicine": "Internal Medicine",
    "systems biology": "Computational Biology",
    "orthopedics": "Orthopedics",
    "orthopedic": "Orthopedics",
    "orthopedic surgery": "Orthopedics",
    "radiology": "Radiology",
    "hepatology": "Hepatology",
    "surgery": "Surgery",
    "methodology": "Other",
    "mechanism": "Other",
    "diagnosis": "Other",
    "prognosis": "Other",
    "other": "Other",
    "pharmacology": "Pharmacology",
    "clinical pharmacology": "Pharmacology",
    "pharmacovigilance": "Pharmacology",
    "pharmacogenomics": "Pharmacology",
    "cell biology": "Cell Biology",
    "cell_biology": "Cell Biology",
    "developmental biology": "Cell Biology",
    "molecular biology": "Molecular Biology",
    "molecular_biology": "Molecular Biology",
    "biochemistry": "Molecular Biology",
    "proteomics": "Molecular Biology",
    "urology": "Urology",
    "critical care": "Critical Care",
    "critical care medicine": "Critical Care",
    "intensive_care": "Critical Care",
    "otolaryngology": "Otolaryngology",
    "epidemiology": "Epidemiology",
    "biostatistics": "Epidemiology",
    "anesthesiology": "Anesthesiology",
    "rehabilitation": "Rehabilitation Medicine",
    "rehabilitation medicine": "Rehabilitation Medicine",
    "rehabilitation/physical medicine": "Rehabilitation Medicine",
    "reproductive medicine": "Reproductive Medicine",
    "reproductive_medicine": "Reproductive Medicine",
    "reproductive_biology": "Reproductive Medicine",
    "reproductive": "Reproductive Medicine",
    "reproductive health": "Reproductive Medicine",
    "pediatrics": "Pediatrics",
    "neonatology": "Pediatrics",
    "gerontology": "Geriatrics",
    "gerontology_aging": "Geriatrics",
    "addiction medicine": "Addiction Medicine",
    "addiction psychiatry": "Addiction Medicine",
    "addiction neurobiology": "Addiction Medicine",
    "toxicology": "Toxicology",
    "microbiology": "Microbiology",
    "environmental health": "Environmental Health",
    "environmental_health": "Environmental Health",
    "occupational": "Public Health",
    "occupational health": "Public Health",
    "public health": "Public Health",
    "health policy": "Public Health",
    "health_policy": "Public Health",
    "healthcare delivery": "Public Health",
    "healthcare_management": "Public Health",
    "health_services_research": "Public Health",
    "health_informatics": "Medical Informatics",
    "medical informatics": "Medical Informatics",
    "medical ai": "Medical Informatics",
    "healthcare ai": "Medical Informatics",
    "healthcare ai security": "Medical Informatics",
    "digital health": "Medical Informatics",
    "primary care": "Internal Medicine",
    "palliative care": "Palliative Care",
    "emergency medicine": "Emergency Medicine",
    "nutrition": "Nutrition",
    "nutrition science": "Nutrition",
    "vascular surgery": "Surgery",
    "cardiac surgery": "Surgery",
    "transplant medicine": "Transplant Medicine",
    "transplant surgery": "Transplant Medicine",
    "transplantation": "Transplant Medicine",
    "veterinary medicine": "Veterinary Medicine",
    "veterinary emergency medicine": "Veterinary Medicine",
    "veterinary dentistry": "Veterinary Medicine",
    "gene therapy": "Genetics & Genomics",
    "bioethics": "Other",
    "neurosurgery": "Neurosurgery",
    "vascular medicine": "Cardiology",
    "vascular_disease": "Cardiology",
    "musculoskeletal": "Orthopedics",
    "gastrointestinal": "Gastroenterology",
    "neurodegenerative": "Neurology",
    "neurodegenerative disease": "Neurology",
    "neurodegenerative_disease": "Neurology",
    "neuroimmunology": "Neurology",
    "neuromuscular": "Neurology",
    "neuromuscular medicine": "Neurology",
    "neuromuscular disorders": "Neurology",
    "neuropharmacology": "Pharmacology",
    "neurological": "Neurology",
    "stroke": "Neurology",
    "pediatric neurology": "Neurology",
    "pediatric oncology": "Oncology",
    "pediatric nephrology": "Nephrology",
    "pediatric cardiology": "Cardiology",
    "pediatric cardiac surgery": "Surgery",
    "pediatric surgery": "Surgery",
    "pediatric psychiatry": "Psychiatry",
    "pediatric endocrinology": "Endocrinology",
    "child and adolescent psychiatry": "Psychiatry",
    "neuro-oncology": "Oncology",
    "cardio-oncology": "Oncology",
    "surgical oncology": "Oncology",
    "thoracic oncology": "Oncology",
    "gynecologic oncology": "Oncology",
    "hematologic malignancy": "Hematology",
    "immuno-oncology": "Oncology",
    "interventional cardiology": "Cardiology",
    "interventional radiology": "Radiology",
    "nanomedicine": "Biomedical Engineering",
    "tissue engineering": "Biomedical Engineering",
    "regenerative medicine": "Biomedical Engineering",
    "transplant immunology": "Transplant Medicine",
    "computational biology": "Computational Biology",
    "medical_education": "Other",
    "medical education": "Other",
    "ethology": "Other",
    "anatomy": "Other",
    "clinical trial design": "Epidemiology",
    "chronic_disease": "Internal Medicine",
    "chronic disease": "Internal Medicine",
    "metabolic": "Endocrinology",
    "metabolic signaling": "Endocrinology",
    "lipidology": "Endocrinology",
    "alternative_medicine": "Other",
    "immunotherapy": "Oncology",
    "parasitology": "Infectious Disease",
    "vaccinology": "Infectious Disease",
    "virology": "Infectious Disease",
    "mycology": "Infectious Disease",

    # --- Disease names as domains ---
    "cystic fibrosis": "Pulmonology",
    "vitiligo": "Dermatology",
    "ovarian cancer": "Oncology",
    "gastric cancer": "Oncology",
    "advanced malignant tumor": "Oncology",
    "advanced solid tumor": "Oncology",
    "breast cancer": "Oncology",
    "human epidermal growth factor 2 negative carcinoma of breast": "Oncology",
    "chronic lymphocytic leukemia": "Hematology",
    "head & neck oncology": "Oncology",
    "amyloidosis": "Internal Medicine",
    "protein aggregation diseases": "Neurology",
    "takotsubo cardiomyopathy": "Cardiology",
    "anosognosia": "Neurology",
    "major depressive disorder": "Psychiatry",
    "cognitive impairment": "Neurology",
    "invasive fungal disease": "Infectious Disease",
    "staphylococcal infections": "Infectious Disease",
    "hcv infection": "Infectious Disease",
    "sepsis syndrome": "Critical Care",
    "relapsing multiple sclerosis": "Neurology",
    "hereditary transthyretin amyloidosis": "Neurology",
    "heart disease": "Cardiology",
    "breakthrough pain": "Pain Medicine",
    "breakthrough cancer pain": "Pain Medicine",
    "chronic hepatitis b virus treatment": "Hepatology",
    "cystinosis": "Nephrology",
    "bacterial vaginosis": "Obstetrics & Gynecology",
    "osteopenia": "Endocrinology",
    "vasomotor symptoms associated with menopause": "Obstetrics & Gynecology",
    "reduced physical activity": "Rehabilitation Medicine",
    "healthy volunteers": "Other",
    "grief": "Psychiatry",
    "tobacco dependence": "Addiction Medicine",
    "obesity management": "Endocrinology",
    "bariatric medicine": "Endocrinology",
    "pediatric obesity": "Pediatrics",
    "syndrome x": "Cardiology",
    "cancer": "Oncology",
    "burn wound healing": "Surgery",

    # --- Non-medical ---
    "botany": "Other",
    "plant physiology": "Other",
    "entomology/insect physiology": "Other",
    "marine_biology": "Other",
    "marine biology": "Other",
    "marine microbiology": "Other",
    "astrobiology": "Other",
    "paleontology": "Other",
    "comparative neurobiology": "Neuroscience",
    "animal behavior/neurobiology": "Neuroscience",
    "agricultural genomics": "Other",
    "mathematical_biology": "Computational Biology",
    "phylogenetics": "Computational Biology",
    "evolutionary biology": "Genetics & Genomics",

    # --- Bioinformatics/Genomics underscored variants ---
    "drug_discovery_computational_chemistry": "Pharmacology",
    "drug_discovery_cheminformatics": "Pharmacology",
    "genomics_sequencing": "Genetics & Genomics",
    "genomics_genetic_risk_prediction": "Genetics & Genomics",
    "genomics_variant_interpretation": "Genetics & Genomics",
    "genomics_genome_annotation": "Genetics & Genomics",
    "genomics_sequencing_analysis": "Genetics & Genomics",
    "genomics_chip_seq": "Genetics & Genomics",
    "genomics_gwas": "Genetics & Genomics",
    "genomics_sequence_analysis": "Genetics & Genomics",
    "genomics_machine_learning": "Genetics & Genomics",
    "genomics_sequence_assembly": "Genetics & Genomics",
    "genomics_rna_seq": "Genetics & Genomics",
    "genomics_genetics": "Genetics & Genomics",
    "proteomics_mass_spectrometry": "Molecular Biology",
    "epigenomics_methylation": "Genetics & Genomics",
    "medical_informatics_ontology": "Medical Informatics",
    "microbiome_analysis": "Microbiology",
}

# Keywords in the (lowercased) primary part that map to canonical domains
KEYWORD_MAP = [
    ("oncol", "Oncology"),
    ("cancer", "Oncology"),
    ("tumor", "Oncology"),
    ("malignan", "Oncology"),
    ("sarcoma", "Oncology"),
    ("leukemia", "Hematology"),
    ("lymphoma", "Hematology"),
    ("cardiol", "Cardiology"),
    ("cardiovasc", "Cardiology"),
    ("cardiac", "Cardiology"),
    ("heart", "Cardiology"),
    ("arrhythm", "Cardiology"),
    ("electrophysiol", "Cardiology"),
    ("atheroscl", "Cardiology"),
    ("neurolog", "Neurology"),
    ("neurodegen", "Neurology"),
    ("neuroimag", "Neurology"),
    ("neuropath", "Neurology"),
    ("neurotraum", "Neurology"),
    ("neuromusc", "Neurology"),
    ("neuroimmun", "Neurology"),
    ("epilep", "Neurology"),
    ("parkinson", "Neurology"),
    ("alzheimer", "Neurology"),
    ("dementia", "Neurology"),
    ("als", "Neurology"),
    ("stroke", "Neurology"),
    ("neurosci", "Neuroscience"),
    ("neurobiol", "Neuroscience"),
    ("neurochem", "Neuroscience"),
    ("neurocircuit", "Neuroscience"),
    ("neuroplastic", "Neuroscience"),
    ("neuroinflam", "Neuroscience"),
    ("neurophysiol", "Neuroscience"),
    ("neuropharmacol", "Pharmacology"),
    ("neurosurg", "Neurosurgery"),
    ("psychiatr", "Psychiatry"),
    ("psychopharmacol", "Psychiatry"),
    ("mental health", "Psychiatry"),
    ("dermatol", "Dermatology"),
    ("endocrinol", "Endocrinology"),
    ("diabet", "Endocrinology"),
    ("metabol", "Endocrinology"),
    ("thyroid", "Endocrinology"),
    ("obesity", "Endocrinology"),
    ("bariatric", "Endocrinology"),
    ("gastroenterol", "Gastroenterology"),
    ("gastrointestin", "Gastroenterology"),
    ("hepatol", "Hepatology"),
    ("liver", "Hepatology"),
    ("hepat", "Hepatology"),
    ("nephrolog", "Nephrology"),
    ("renal", "Nephrology"),
    ("dialysis", "Nephrology"),
    ("kidney", "Nephrology"),
    ("pulmonol", "Pulmonology"),
    ("pulmonar", "Pulmonology"),
    ("respirat", "Pulmonology"),
    ("lung", "Pulmonology"),
    ("hematol", "Hematology"),
    ("immunol", "Immunology"),
    ("autoimmun", "Immunology"),
    ("rheumatol", "Rheumatology"),
    ("ophthalm", "Ophthalmology"),
    ("otolaryngol", "Otolaryngology"),
    ("ent ", "Otolaryngology"),
    ("orthoped", "Orthopedics"),
    ("obstetric", "Obstetrics & Gynecology"),
    ("gynecol", "Obstetrics & Gynecology"),
    ("maternal", "Obstetrics & Gynecology"),
    ("perinatal", "Obstetrics & Gynecology"),
    ("reproduct", "Reproductive Medicine"),
    ("fertil", "Reproductive Medicine"),
    ("contracep", "Reproductive Medicine"),
    ("pediatr", "Pediatrics"),
    ("neonat", "Pediatrics"),
    ("geriatr", "Geriatrics"),
    ("gerontol", "Geriatrics"),
    ("aging", "Geriatrics"),
    ("infect", "Infectious Disease"),
    ("parasit", "Infectious Disease"),
    ("virol", "Infectious Disease"),
    ("mycol", "Infectious Disease"),
    ("mycobact", "Infectious Disease"),
    ("vaccin", "Infectious Disease"),
    ("antimicrob", "Infectious Disease"),
    ("hiv", "Infectious Disease"),
    ("tubercul", "Infectious Disease"),
    ("tropical", "Infectious Disease"),
    ("sepsis", "Critical Care"),
    ("addict", "Addiction Medicine"),
    ("substance", "Addiction Medicine"),
    ("tobacco", "Addiction Medicine"),
    ("smoking", "Addiction Medicine"),
    ("pharmacol", "Pharmacology"),
    ("pharmacog", "Pharmacology"),
    ("drug dis", "Pharmacology"),
    ("drug dev", "Pharmacology"),
    ("medicin", "Pharmacology"),
    ("pharmac", "Pharmacology"),
    ("radiol", "Radiology"),
    ("imaging", "Radiology"),
    ("radiatio", "Oncology"),
    ("transplant", "Transplant Medicine"),
    ("surger", "Surgery"),
    ("surgical", "Surgery"),
    ("wound", "Surgery"),
    ("burn", "Surgery"),
    ("dentist", "Dentistry"),
    ("periodon", "Dentistry"),
    ("oral", "Dentistry"),
    ("maxillof", "Dentistry"),
    ("urolog", "Urology"),
    ("sexual", "Urology"),
    ("pathol", "Pathology"),
    ("toxicol", "Toxicology"),
    ("anesthes", "Anesthesiology"),
    ("pain", "Pain Medicine"),
    ("palliative", "Palliative Care"),
    ("rehab", "Rehabilitation Medicine"),
    ("genet", "Genetics & Genomics"),
    ("genom", "Genetics & Genomics"),
    ("epigenet", "Genetics & Genomics"),
    ("bioinform", "Computational Biology"),
    ("computat", "Computational Biology"),
    ("system", "Computational Biology"),
    ("mathemat", "Computational Biology"),
    ("cell biol", "Cell Biology"),
    ("cell_biol", "Cell Biology"),
    ("molecul", "Molecular Biology"),
    ("proteom", "Molecular Biology"),
    ("biochem", "Molecular Biology"),
    ("biophys", "Molecular Biology"),
    ("structur", "Molecular Biology"),
    ("microbi", "Microbiology"),
    ("microbiom", "Microbiology"),
    ("environm", "Environmental Health"),
    ("occupa", "Public Health"),
    ("public health", "Public Health"),
    ("health polic", "Public Health"),
    ("epidemi", "Epidemiology"),
    ("biostatist", "Epidemiology"),
    ("nutrit", "Nutrition"),
    ("emergen", "Emergency Medicine"),
    ("critical care", "Critical Care"),
    ("intensive care", "Critical Care"),
    ("veterina", "Veterinary Medicine"),
    ("nanomed", "Biomedical Engineering"),
    ("biomateri", "Biomedical Engineering"),
    ("tissue eng", "Biomedical Engineering"),
    ("regenerat", "Biomedical Engineering"),
    ("biomedical eng", "Biomedical Engineering"),
    ("medical ai", "Medical Informatics"),
    ("health inform", "Medical Informatics"),
    ("health it", "Medical Informatics"),
    ("telemedi", "Medical Informatics"),
    ("digital health", "Medical Informatics"),
    ("medical inform", "Medical Informatics"),
    ("stem cell", "Cell Biology"),
    ("immunother", "Oncology"),
]


def normalize_domain(raw: str) -> str:
    if not raw or not raw.strip():
        return "Other"

    s = raw.strip()
    s = s.replace("_", " ")
    s_lower = s.lower().strip()

    if s_lower in DIRECT_MAP:
        return DIRECT_MAP[s_lower]

    # Split compound domains: take first part
    # Separators: " / ", "/", ", ", ","
    for sep in [" / ", "/", ", ", ","]:
        if sep in s:
            parts = [p.strip() for p in s.split(sep) if p.strip()]
            if parts:
                first = parts[0].replace("_", " ").lower().strip()
                if first in DIRECT_MAP:
                    return DIRECT_MAP[first]
                # Try keyword match on the first part
                for kw, canonical in KEYWORD_MAP:
                    if kw in first:
                        return canonical
                # If first part didn't match, try all parts
                for part in parts:
                    part_lower = part.replace("_", " ").lower().strip()
                    if part_lower in DIRECT_MAP:
                        return DIRECT_MAP[part_lower]
                # Keyword match on all parts
                for part in parts:
                    part_lower = part.replace("_", " ").lower().strip()
                    for kw, canonical in KEYWORD_MAP:
                        if kw in part_lower:
                            return canonical

    # Try keyword match on the full string
    for kw, canonical in KEYWORD_MAP:
        if kw in s_lower:
            return canonical

    return "Other"


def main():
    input_file = "/data/project/private/minstar/workspace/healthcare-research/data/extracted/all_questions_final.jsonl"
    output_file = input_file  # in-place

    questions = []
    with open(input_file) as f:
        for line in f:
            line = line.strip()
            if line:
                questions.append(json.loads(line))

    old_domains = Counter()
    new_domains = Counter()
    changes = 0

    for q in questions:
        old = q.get("clinical_domain", "")
        old_domains[old] += 1
        new = normalize_domain(old)
        new_domains[new] += 1
        if old != new:
            changes += 1
        q["clinical_domain"] = new

    with open(output_file, "w") as f:
        for q in questions:
            f.write(json.dumps(q, ensure_ascii=False) + "\n")

    print(f"Normalized {changes}/{len(questions)} entries")
    print(f"Domains: {len(old_domains)} -> {len(new_domains)}")
    print(f"\n{'Domain':<30} {'Count':>6}")
    print("-" * 38)
    for d, c in new_domains.most_common():
        print(f"{d:<30} {c:>6}")


if __name__ == "__main__":
    main()
